#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/bj/app/                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : smile                                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Empowering Autism with AI

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Abdelrhman Abdelhalim                                
your_link                                 :                     
your_city                                 :                                 
email_address                             : abdelrhmanbdlhlm@gmail.com
facebook_username                         : profile.php?id=61573076334312                                      
instagram_username                        : smile_app1
twitter_username                          : 
github_username                           : abdelrhmanidk
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : AI-Powered Assistance
    description                           : Utilizes AI to enhance communication, learning, and engagement for children with autism.
    fontawesome_icon_name                 : brain

  - title                                 : Interactive Learning
    description                           : Provides fun and engaging exercises tailored to each child’s unique needs.
    fontawesome_icon_name                 : puzzle-piece

  - title                                 : Personalized Experience
    description                           : Adapts to each child’s learning style with customized activities and feedback.
    fontawesome_icon_name                 : user-cog

  - title                                 : Visual & Audio Support
    description                           : Uses images, text-to-speech, and sound cues to enhance understanding.
    fontawesome_icon_name                 : volume-up

  - title                                 : Parent Dashboard
    description                           : Allows parents to monitor progress and track improvements over time.
    fontawesome_icon_name                 : chart-line

  - title                                 : Safe & Secure
    description                           : Designed with child safety in mind, ensuring a distraction-free and protected environment.
    fontawesome_icon_name                 : shield-alt

  - title                                 : Multi-Device Compatibility
    description                           : Works seamlessly on smartphones, tablets, and other devices.
    fontawesome_icon_name                 : mobile

  - title                                 : Social & Emotional Learning
    description                           : Helps children develop social skills and emotional recognition through AI-powered exercises.
    fontawesome_icon_name                 : heart

  - title                                 : Easy Setup & Customization
    description                           : Simple onboarding process with options to customize activities and preferences.
    fontawesome_icon_name                 : cogs

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/appicon.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
